title: Aditya Vedanthu
logo: <img width="222" height="183" alt="dp" src="https://github.com/user-attachments/assets/abd9dde9-d15f-458e-9930-df3267d7f329" />
description: Aditya Vedanthu - Problem Solver and Innovator in Engineering
show_downloads: true
theme: jekyll-theme-minimal
